stages:

  data_ingestion:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_01_data_ingestion
    deps:
      - src/pipeline/stage_01_data_ingestion.py
      - src/components/data_ingestion.py
      - config/config.yaml
    outs:
      - data/raw
  data_preparation:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_02_data_preparation
    deps:
      - src/pipeline/stage_02_data_preparation.py
      - src/components/data_preparation.py
      - data/raw
    outs:
      - data/interim
      - data/processed

  mri_preprocessing:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_03_mri_preprocessing
    deps:
      - src/pipeline/stage_03_mri_preprocessing.py
      - src/components/mri_preprocessing.py
      - data/interim
      - data/processed
    outs:
      - data/preprocessed

  feature_extraction:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_04_feature_extraction
    deps:
      - src/pipeline/stage_04_feature_extraction.py
      - src/components/feature_extraction.py
      - data/preprocessed
    outs:
      - artifacts/features
  # morphometric_feature_extraction:
  #   cmd: set PYTHONPATH=. && python -m src.pipeline.stage_04b_morphometric_feature_extraction
  #   deps:
  #     - src/pipeline/stage_04b_morphometric_feature_extraction.py
  #     - src/components/morphometric_feature_extraction.py
  #     - data/processed
  #   outs:
  #     - artifacts/morphometric_features


  # feature_aggregation:
  #   cmd: set PYTHONPATH=. && python -m src.pipeline.stage_05_feature_aggregation
  #   deps:
  #     - src/pipeline/stage_05_feature_aggregation.py
  #     - src/components/feature_aggregation.py
  #     - artifacts/features
  #     - artifacts/morphometric_features
  #   outs:
  #     - artifacts/aggregated_features
  feature_scaling:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_05b_feature_scaling
    deps:
      - src/pipeline/stage_05b_feature_scaling.py
      - src/components/feature_scaling.py
      - artifacts/features
    outs:
      - artifacts/scaled_features

  feature_selection:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_06_feature_selection
    deps:
      - src/pipeline/stage_06_feature_selection.py
      - src/components/feature_selection.py
      - artifacts/scaled_features
    outs:
      - artifacts/feature_selection


  model_training:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_07_model_training
    deps:
      - src/pipeline/stage_07_model_training.py
      - src/components/model_training.py
      - artifacts/feature_selection
    outs:
      - artifacts/model_training


  model_evaluation:
    cmd: set PYTHONPATH=. && python -m src.pipeline.stage_08_model_evaluation
    deps:
      - src/pipeline/stage_08_model_evaluation.py
      - src/components/model_evaluation.py
      - artifacts/model_training
      - artifacts/feature_selection
    outs:
      - artifacts/model_evaluation